flask:
  init:
    import_name: televy
    template_folder: views
    static_folder: static
    static_url_path: /static
  config:
    SECRET_KEY: 'J\x1dg\xc2?\xaf3#\x82\x0e|\xf1\xb3\x06R\xf2+M\x92\xfb\xa1\x101\x9c'
    ASSETS_DEBUG: false

televy_info:
  version: local

debug:
  enabled: true
  server:
    host: 0.0.0.0
    port: 4501

views:
  - main
  - televy.controllers.health_controller

logging:
  version: 1
  formatters:
    default:
      format: "%(asctime)s - %(levelname)s - %(message)s"
  handlers:
    televy_run:
      class : logging.handlers.TimedRotatingFileHandler
      formatter: default
      level: INFO
      filename: log/televy_run.log
      when: D
      backupCount: 7
  loggers:
    televy.run:
      level: INFO
      propagate: false
      handlers: [televy_run]
